"""Formal Claim IR (v3-formal, schema v1.1).

Executable logical-statistical claim objects — the ⟨P, O, S, I, C⟩ 5-tuple.

Spec: internal/epistemic_os/13_FORMAL_CLAIM_IR.md §3 (v1.1).
Fixtures: internal/epistemic_os/fixtures/*.json.
"""

from polymer_genomics.formal_claims.evaluate import (
    EVALUATOR_VERSION,
    CmpEvaluation,
    EvaluationResult,
    MaterializationStatus,
    StatDrift,
    Verdict,
    evaluate,
    walk_fixtures,
)
from polymer_genomics.formal_claims.feature_extractor import (
    FEATURE_DIM,
    FEATURE_NAMES,
    INSILICO_ROOT,
    build_feature_matrix,
    extract_features,
    load_all_formal_claims,
)
from polymer_genomics.formal_claims.nanopub import to_trig
from polymer_genomics.formal_claims.projection import ProjectionResult, project
from polymer_genomics.formal_claims.schema import (
    SCHEMA_VERSION,
    SCHEMA_VERSIONS_SUPPORTED,
    Agg,
    AggregateOp,
    AndExpr,
    Audit,
    CmpExpr,
    # v1.2 subject slot
    Cohort,
    CohortDefinition,
    CohortSourceDataset,
    CompositeConfidence,
    CompositeSubject,
    # Conclusion
    Conclusion,
    CorrectOp,
    CVScheme,
    CVSplitOp,
    DataDerivedConstant,
    # v1.2 domain
    Domain,
    EstimatorOp,
    EstimatorSpec,
    EvidenceClass,
    # External
    ExternalAssumption,
    FeatureSet,
    FilterOp,
    # Root
    FormalClaim,
    GeneOrProtein,
    GeneOrProteinIdentifiers,
    GenomicRegion,
    InferenceExpression,
    # Inference
    InferenceRule,
    JoinExpr,
    JoinOp,
    # Shared
    LayerRef,
    LiteralSubject,
    LiteralSubjectStructured,
    NotExpr,
    NullModelOp,
    NullModelSpec,
    OntologyTerm,
    # Operations
    Operation,
    OrExpr,
    Outcome,
    PathwayMembers,
    PathwayRef,
    PhenopacketRef,
    PhenopacketRetrieval,
    # Premises
    Premise,
    ProjectOp,
    ProvenanceState,
    S4ObjectRef,
    # Predicates
    SetExpression,
    # Statistics
    Statistic,
    StatRef,
    SubjectRef,
    VariantVRS,
)

__all__ = [
    "SCHEMA_VERSION",
    "SCHEMA_VERSIONS_SUPPORTED",
    "LayerRef",
    "ProvenanceState",
    "EvidenceClass",
    "FeatureSet",
    "DataDerivedConstant",
    "SetExpression",
    "AndExpr",
    "OrExpr",
    "NotExpr",
    "CmpExpr",
    "JoinExpr",
    "Premise",
    "Operation",
    "FilterOp",
    "ProjectOp",
    "JoinOp",
    "AggregateOp",
    "CVSplitOp",
    "EstimatorOp",
    "NullModelOp",
    "CorrectOp",
    "Agg",
    "CVScheme",
    "EstimatorSpec",
    "NullModelSpec",
    "Statistic",
    "InferenceRule",
    "InferenceExpression",
    "StatRef",
    "Conclusion",
    "CompositeConfidence",
    "Outcome",
    "ExternalAssumption",
    "Audit",
    "FormalClaim",
    # v1.2 domain + subject slot
    "Domain",
    "SubjectRef",
    "GenomicRegion",
    "VariantVRS",
    "S4ObjectRef",
    "PhenopacketRef",
    "PhenopacketRetrieval",
    "OntologyTerm",
    "GeneOrProtein",
    "GeneOrProteinIdentifiers",
    "PathwayRef",
    "PathwayMembers",
    "Cohort",
    "CohortDefinition",
    "CohortSourceDataset",
    "LiteralSubject",
    "LiteralSubjectStructured",
    "CompositeSubject",
    # Projection
    "FEATURE_DIM",
    "FEATURE_NAMES",
    "INSILICO_ROOT",
    "extract_features",
    "build_feature_matrix",
    "load_all_formal_claims",
    "ProjectionResult",
    "project",
    # Evaluation
    "EVALUATOR_VERSION",
    "CmpEvaluation",
    "EvaluationResult",
    "MaterializationStatus",
    "StatDrift",
    "Verdict",
    "evaluate",
    "walk_fixtures",
    # Nanopub interop
    "to_trig",
]
