// src/lib/transposome-mock.ts
// Static mock data for Transposome Explorer development.
// ~30 representative TE families spanning the full evolutionary landscape.

import type { TEFamily, TEFamilyDetail } from './transposome-types';

export const MOCK_FAMILIES: TEFamily[] = [
  // ── Young, active elements ──────────────────────────────────────────
  {
    id: 'HERVK_HML2',
    display_name: 'HERV-K (HML-2)',
    class: 'LTR',
    family: 'ERVK',
    divergence_pct: 2.3,
    copy_count: 1_200,
    total_bp: 11_400_000,
    consensus_length: 9_472,
    cpg_density: 1.14,
    gc_content: 0.482,
    stacking_dg37: -1.42,
    wrapping_energy: 17.8,
    ndr_score: 0.45,
    periodicity_power: 0.35,
    silencing_primary: 'mixed',
    silencing_confidence: 0.92,
    reactivation_score: 0.90,
    reactivation_contexts: ['aging', 'dnmti', 'tet2_lof', 'setdb1_lof'],
    epic_v2_probes: 127,
    retro_age_probes: 18,
    has_intact_orfs: true,
    is_active: true,
    clinically_implicated: true,
  },
  {
    id: 'L1HS',
    display_name: 'L1HS',
    class: 'LINE',
    family: 'L1',
    divergence_pct: 1.5,
    copy_count: 1_500,
    total_bp: 9_000_000,
    consensus_length: 6_019,
    cpg_density: 0.42,
    gc_content: 0.395,
    stacking_dg37: -1.28,
    wrapping_energy: 15.9,
    ndr_score: 0.30,
    periodicity_power: 0.22,
    silencing_primary: 'methylation',
    silencing_confidence: 0.95,
    reactivation_score: 0.75,
    reactivation_contexts: ['aging', 'dnmti', 'tet2_lof'],
    epic_v2_probes: 89,
    retro_age_probes: 12,
    has_intact_orfs: true,
    is_active: true,
    clinically_implicated: true,
  },
  {
    id: 'AluY',
    display_name: 'AluY',
    class: 'SINE',
    family: 'Alu',
    divergence_pct: 3.1,
    copy_count: 125_000,
    total_bp: 37_500_000,
    consensus_length: 300,
    cpg_density: 1.10,
    gc_content: 0.623,
    stacking_dg37: -1.68,
    wrapping_energy: 20.5,
    ndr_score: 0.38,
    periodicity_power: 0.55,
    silencing_primary: 'methylation',
    silencing_confidence: 0.88,
    reactivation_score: 0.30,
    reactivation_contexts: ['dnmti'],
    epic_v2_probes: 2_400,
    retro_age_probes: 45,
    has_intact_orfs: false,
    is_active: true,
    clinically_implicated: false,
  },
  {
    id: 'SVA_E',
    display_name: 'SVA-E',
    class: 'SVA',
    family: 'SVA',
    divergence_pct: 1.8,
    copy_count: 3_000,
    total_bp: 6_000_000,
    consensus_length: 2_000,
    cpg_density: 0.95,
    gc_content: 0.552,
    stacking_dg37: -1.55,
    wrapping_energy: 19.2,
    ndr_score: 0.42,
    periodicity_power: 0.48,
    silencing_primary: 'mixed',
    silencing_confidence: 0.85,
    reactivation_score: 0.60,
    reactivation_contexts: ['dnmti', 'setdb1_lof'],
    epic_v2_probes: 34,
    retro_age_probes: 5,
    has_intact_orfs: false,
    is_active: true,
    clinically_implicated: false,
  },

  // ── Intermediate-age elements ───────────────────────────────────────
  {
    id: 'HERVH',
    display_name: 'HERV-H',
    class: 'LTR',
    family: 'ERVH',
    divergence_pct: 7.5,
    copy_count: 1_000,
    total_bp: 7_500_000,
    consensus_length: 7_400,
    cpg_density: 0.68,
    gc_content: 0.445,
    stacking_dg37: -1.35,
    wrapping_energy: 16.8,
    ndr_score: 0.35,
    periodicity_power: 0.30,
    silencing_primary: 'h3k9me3',
    silencing_confidence: 0.80,
    reactivation_score: 0.45,
    reactivation_contexts: ['setdb1_lof'],
    epic_v2_probes: 85,
    retro_age_probes: 8,
    has_intact_orfs: false,
    is_active: false,
    clinically_implicated: true,
  },
  {
    id: 'L1PA2',
    display_name: 'L1PA2',
    class: 'LINE',
    family: 'L1',
    divergence_pct: 4.2,
    copy_count: 5_500,
    total_bp: 33_000_000,
    consensus_length: 6_019,
    cpg_density: 0.35,
    gc_content: 0.388,
    stacking_dg37: -1.25,
    wrapping_energy: 15.6,
    ndr_score: 0.28,
    periodicity_power: 0.20,
    silencing_primary: 'methylation',
    silencing_confidence: 0.90,
    reactivation_score: 0.55,
    reactivation_contexts: ['aging', 'dnmti'],
    epic_v2_probes: 65,
    retro_age_probes: 9,
    has_intact_orfs: false,
    is_active: false,
    clinically_implicated: false,
  },
  {
    id: 'L1PA3',
    display_name: 'L1PA3',
    class: 'LINE',
    family: 'L1',
    divergence_pct: 5.8,
    copy_count: 8_200,
    total_bp: 49_200_000,
    consensus_length: 6_019,
    cpg_density: 0.32,
    gc_content: 0.385,
    stacking_dg37: -1.24,
    wrapping_energy: 15.5,
    ndr_score: 0.26,
    periodicity_power: 0.19,
    silencing_primary: 'methylation',
    silencing_confidence: 0.88,
    reactivation_score: 0.40,
    reactivation_contexts: ['dnmti'],
    epic_v2_probes: 52,
    retro_age_probes: 6,
    has_intact_orfs: false,
    is_active: false,
    clinically_implicated: false,
  },
  {
    id: 'L1PA4',
    display_name: 'L1PA4',
    class: 'LINE',
    family: 'L1',
    divergence_pct: 7.5,
    copy_count: 9_800,
    total_bp: 58_800_000,
    consensus_length: 6_019,
    cpg_density: 0.30,
    gc_content: 0.382,
    stacking_dg37: -1.22,
    wrapping_energy: 15.3,
    ndr_score: 0.24,
    periodicity_power: 0.18,
    silencing_primary: 'methylation',
    silencing_confidence: 0.85,
    reactivation_score: 0.30,
    reactivation_contexts: ['dnmti'],
    epic_v2_probes: 42,
    retro_age_probes: 4,
    has_intact_orfs: false,
    is_active: false,
    clinically_implicated: false,
  },
  {
    id: 'L1PA5',
    display_name: 'L1PA5',
    class: 'LINE',
    family: 'L1',
    divergence_pct: 9.0,
    copy_count: 11_500,
    total_bp: 69_000_000,
    consensus_length: 6_019,
    cpg_density: 0.28,
    gc_content: 0.380,
    stacking_dg37: -1.21,
    wrapping_energy: 15.2,
    ndr_score: 0.22,
    periodicity_power: 0.17,
    silencing_primary: 'h3k9me3',
    silencing_confidence: 0.78,
    reactivation_score: 0.20,
    reactivation_contexts: [],
    epic_v2_probes: 35,
    retro_age_probes: 3,
    has_intact_orfs: false,
    is_active: false,
    clinically_implicated: false,
  },
  {
    id: 'AluSx',
    display_name: 'AluSx',
    class: 'SINE',
    family: 'Alu',
    divergence_pct: 8.5,
    copy_count: 400_000,
    total_bp: 120_000_000,
    consensus_length: 300,
    cpg_density: 0.82,
    gc_content: 0.598,
    stacking_dg37: -1.60,
    wrapping_energy: 19.8,
    ndr_score: 0.32,
    periodicity_power: 0.50,
    silencing_primary: 'methylation',
    silencing_confidence: 0.82,
    reactivation_score: 0.15,
    reactivation_contexts: [],
    epic_v2_probes: 3_200,
    retro_age_probes: 22,
    has_intact_orfs: false,
    is_active: false,
    clinically_implicated: false,
  },
  {
    id: 'AluSp',
    display_name: 'AluSp',
    class: 'SINE',
    family: 'Alu',
    divergence_pct: 6.5,
    copy_count: 85_000,
    total_bp: 25_500_000,
    consensus_length: 300,
    cpg_density: 0.90,
    gc_content: 0.608,
    stacking_dg37: -1.63,
    wrapping_energy: 20.0,
    ndr_score: 0.34,
    periodicity_power: 0.52,
    silencing_primary: 'methylation',
    silencing_confidence: 0.84,
    reactivation_score: 0.20,
    reactivation_contexts: [],
    epic_v2_probes: 1_800,
    retro_age_probes: 15,
    has_intact_orfs: false,
    is_active: false,
    clinically_implicated: false,
  },
  {
    id: 'AluSq',
    display_name: 'AluSq',
    class: 'SINE',
    family: 'Alu',
    divergence_pct: 7.2,
    copy_count: 95_000,
    total_bp: 28_500_000,
    consensus_length: 300,
    cpg_density: 0.88,
    gc_content: 0.605,
    stacking_dg37: -1.62,
    wrapping_energy: 19.9,
    ndr_score: 0.33,
    periodicity_power: 0.51,
    silencing_primary: 'methylation',
    silencing_confidence: 0.83,
    reactivation_score: 0.18,
    reactivation_contexts: [],
    epic_v2_probes: 2_100,
    retro_age_probes: 18,
    has_intact_orfs: false,
    is_active: false,
    clinically_implicated: false,
  },
  {
    id: 'ERV1',
    display_name: 'ERV1',
    class: 'LTR',
    family: 'ERV1',
    divergence_pct: 12.0,
    copy_count: 4_500,
    total_bp: 27_000_000,
    consensus_length: 6_000,
    cpg_density: 0.48,
    gc_content: 0.422,
    stacking_dg37: -1.32,
    wrapping_energy: 16.4,
    ndr_score: 0.28,
    periodicity_power: 0.25,
    silencing_primary: 'h3k9me3',
    silencing_confidence: 0.75,
    reactivation_score: 0.25,
    reactivation_contexts: ['setdb1_lof'],
    epic_v2_probes: 45,
    retro_age_probes: 3,
    has_intact_orfs: false,
    is_active: false,
    clinically_implicated: false,
  },
  {
    id: 'HERV_W',
    display_name: 'HERV-W',
    class: 'LTR',
    family: 'ERVW',
    divergence_pct: 10.5,
    copy_count: 650,
    total_bp: 4_550_000,
    consensus_length: 7_000,
    cpg_density: 0.55,
    gc_content: 0.438,
    stacking_dg37: -1.34,
    wrapping_energy: 16.6,
    ndr_score: 0.32,
    periodicity_power: 0.28,
    silencing_primary: 'h3k9me3',
    silencing_confidence: 0.78,
    reactivation_score: 0.35,
    reactivation_contexts: ['aging'],
    epic_v2_probes: 22,
    retro_age_probes: 2,
    has_intact_orfs: false,
    is_active: false,
    clinically_implicated: true,
  },
  {
    id: 'HERVL',
    display_name: 'HERV-L',
    class: 'LTR',
    family: 'ERVL',
    divergence_pct: 14.0,
    copy_count: 800,
    total_bp: 5_600_000,
    consensus_length: 7_000,
    cpg_density: 0.40,
    gc_content: 0.405,
    stacking_dg37: -1.28,
    wrapping_energy: 15.8,
    ndr_score: 0.22,
    periodicity_power: 0.20,
    silencing_primary: 'h3k27me3',
    silencing_confidence: 0.70,
    reactivation_score: 0.12,
    reactivation_contexts: [],
    epic_v2_probes: 18,
    retro_age_probes: 1,
    has_intact_orfs: false,
    is_active: false,
    clinically_implicated: false,
  },
  {
    id: 'HERVK_int',
    display_name: 'HERV-K (internal)',
    class: 'LTR',
    family: 'ERVK',
    divergence_pct: 5.5,
    copy_count: 2_800,
    total_bp: 19_600_000,
    consensus_length: 7_000,
    cpg_density: 0.72,
    gc_content: 0.465,
    stacking_dg37: -1.38,
    wrapping_energy: 17.2,
    ndr_score: 0.40,
    periodicity_power: 0.32,
    silencing_primary: 'mixed',
    silencing_confidence: 0.88,
    reactivation_score: 0.65,
    reactivation_contexts: ['aging', 'dnmti', 'setdb1_lof'],
    epic_v2_probes: 95,
    retro_age_probes: 14,
    has_intact_orfs: false,
    is_active: false,
    clinically_implicated: true,
  },

  // ── Intermediate-old, Polycomb-silenced ─────────────────────────────
  {
    id: 'ERVL_MaLR',
    display_name: 'ERVL-MaLR',
    class: 'LTR',
    family: 'ERVL-MaLR',
    divergence_pct: 15.5,
    copy_count: 240_000,
    total_bp: 120_000_000,
    consensus_length: 500,
    cpg_density: 0.35,
    gc_content: 0.398,
    stacking_dg37: -1.26,
    wrapping_energy: 15.4,
    ndr_score: 0.20,
    periodicity_power: 0.18,
    silencing_primary: 'h3k27me3',
    silencing_confidence: 0.72,
    reactivation_score: 0.10,
    reactivation_contexts: [],
    epic_v2_probes: 28,
    retro_age_probes: 0,
    has_intact_orfs: false,
    is_active: false,
    clinically_implicated: false,
  },
  {
    id: 'AluJb',
    display_name: 'AluJb',
    class: 'SINE',
    family: 'Alu',
    divergence_pct: 14.2,
    copy_count: 280_000,
    total_bp: 84_000_000,
    consensus_length: 300,
    cpg_density: 0.55,
    gc_content: 0.565,
    stacking_dg37: -1.52,
    wrapping_energy: 18.8,
    ndr_score: 0.25,
    periodicity_power: 0.42,
    silencing_primary: 'h3k27me3',
    silencing_confidence: 0.68,
    reactivation_score: 0.05,
    reactivation_contexts: [],
    epic_v2_probes: 1_800,
    retro_age_probes: 5,
    has_intact_orfs: false,
    is_active: false,
    clinically_implicated: false,
  },
  {
    id: 'AluJo',
    display_name: 'AluJo',
    class: 'SINE',
    family: 'Alu',
    divergence_pct: 15.8,
    copy_count: 190_000,
    total_bp: 57_000_000,
    consensus_length: 300,
    cpg_density: 0.50,
    gc_content: 0.555,
    stacking_dg37: -1.50,
    wrapping_energy: 18.5,
    ndr_score: 0.23,
    periodicity_power: 0.40,
    silencing_primary: 'h3k27me3',
    silencing_confidence: 0.65,
    reactivation_score: 0.03,
    reactivation_contexts: [],
    epic_v2_probes: 1_200,
    retro_age_probes: 2,
    has_intact_orfs: false,
    is_active: false,
    clinically_implicated: false,
  },
  {
    id: 'L1M1',
    display_name: 'L1M1',
    class: 'LINE',
    family: 'L1',
    divergence_pct: 18.0,
    copy_count: 22_000,
    total_bp: 88_000_000,
    consensus_length: 4_000,
    cpg_density: 0.22,
    gc_content: 0.372,
    stacking_dg37: -1.18,
    wrapping_energy: 14.8,
    ndr_score: 0.18,
    periodicity_power: 0.15,
    silencing_primary: 'h3k27me3',
    silencing_confidence: 0.62,
    reactivation_score: 0.02,
    reactivation_contexts: [],
    epic_v2_probes: 15,
    retro_age_probes: 0,
    has_intact_orfs: false,
    is_active: false,
    clinically_implicated: false,
  },
  {
    id: 'L1M2',
    display_name: 'L1M2',
    class: 'LINE',
    family: 'L1',
    divergence_pct: 19.5,
    copy_count: 18_000,
    total_bp: 72_000_000,
    consensus_length: 4_000,
    cpg_density: 0.21,
    gc_content: 0.370,
    stacking_dg37: -1.17,
    wrapping_energy: 14.7,
    ndr_score: 0.17,
    periodicity_power: 0.14,
    silencing_primary: 'h3k27me3',
    silencing_confidence: 0.60,
    reactivation_score: 0.01,
    reactivation_contexts: [],
    epic_v2_probes: 12,
    retro_age_probes: 0,
    has_intact_orfs: false,
    is_active: false,
    clinically_implicated: false,
  },
  {
    id: 'L1M3',
    display_name: 'L1M3',
    class: 'LINE',
    family: 'L1',
    divergence_pct: 21.0,
    copy_count: 15_000,
    total_bp: 60_000_000,
    consensus_length: 4_000,
    cpg_density: 0.20,
    gc_content: 0.368,
    stacking_dg37: -1.16,
    wrapping_energy: 14.6,
    ndr_score: 0.16,
    periodicity_power: 0.13,
    silencing_primary: 'none',
    silencing_confidence: 0.55,
    reactivation_score: 0.00,
    reactivation_contexts: [],
    epic_v2_probes: 8,
    retro_age_probes: 0,
    has_intact_orfs: false,
    is_active: false,
    clinically_implicated: false,
  },
  {
    id: 'L1M5',
    display_name: 'L1M5',
    class: 'LINE',
    family: 'L1',
    divergence_pct: 23.0,
    copy_count: 12_000,
    total_bp: 48_000_000,
    consensus_length: 4_000,
    cpg_density: 0.19,
    gc_content: 0.365,
    stacking_dg37: -1.14,
    wrapping_energy: 14.4,
    ndr_score: 0.14,
    periodicity_power: 0.12,
    silencing_primary: 'none',
    silencing_confidence: 0.50,
    reactivation_score: 0.00,
    reactivation_contexts: [],
    epic_v2_probes: 5,
    retro_age_probes: 0,
    has_intact_orfs: false,
    is_active: false,
    clinically_implicated: false,
  },

  // ── Ancient, fossilized elements ────────────────────────────────────
  {
    id: 'MIR',
    display_name: 'MIR',
    class: 'SINE',
    family: 'MIR',
    divergence_pct: 26.5,
    copy_count: 580_000,
    total_bp: 145_000_000,
    consensus_length: 250,
    cpg_density: 0.18,
    gc_content: 0.410,
    stacking_dg37: -1.30,
    wrapping_energy: 16.2,
    ndr_score: 0.20,
    periodicity_power: 0.25,
    silencing_primary: 'none',
    silencing_confidence: 0.90,
    reactivation_score: 0.00,
    reactivation_contexts: [],
    epic_v2_probes: 890,
    retro_age_probes: 0,
    has_intact_orfs: false,
    is_active: false,
    clinically_implicated: false,
  },
  {
    id: 'MIRb',
    display_name: 'MIRb',
    class: 'SINE',
    family: 'MIR',
    divergence_pct: 27.5,
    copy_count: 320_000,
    total_bp: 80_000_000,
    consensus_length: 250,
    cpg_density: 0.17,
    gc_content: 0.405,
    stacking_dg37: -1.29,
    wrapping_energy: 16.0,
    ndr_score: 0.19,
    periodicity_power: 0.24,
    silencing_primary: 'none',
    silencing_confidence: 0.90,
    reactivation_score: 0.00,
    reactivation_contexts: [],
    epic_v2_probes: 520,
    retro_age_probes: 0,
    has_intact_orfs: false,
    is_active: false,
    clinically_implicated: false,
  },
  {
    id: 'MIRc',
    display_name: 'MIRc',
    class: 'SINE',
    family: 'MIR',
    divergence_pct: 28.0,
    copy_count: 210_000,
    total_bp: 52_500_000,
    consensus_length: 250,
    cpg_density: 0.16,
    gc_content: 0.402,
    stacking_dg37: -1.28,
    wrapping_energy: 15.9,
    ndr_score: 0.18,
    periodicity_power: 0.23,
    silencing_primary: 'none',
    silencing_confidence: 0.90,
    reactivation_score: 0.00,
    reactivation_contexts: [],
    epic_v2_probes: 380,
    retro_age_probes: 0,
    has_intact_orfs: false,
    is_active: false,
    clinically_implicated: false,
  },
  {
    id: 'L2',
    display_name: 'L2',
    class: 'LINE',
    family: 'L2',
    divergence_pct: 24.0,
    copy_count: 450_000,
    total_bp: 180_000_000,
    consensus_length: 400,
    cpg_density: 0.20,
    gc_content: 0.385,
    stacking_dg37: -1.24,
    wrapping_energy: 15.4,
    ndr_score: 0.16,
    periodicity_power: 0.18,
    silencing_primary: 'none',
    silencing_confidence: 0.88,
    reactivation_score: 0.00,
    reactivation_contexts: [],
    epic_v2_probes: 420,
    retro_age_probes: 0,
    has_intact_orfs: false,
    is_active: false,
    clinically_implicated: false,
  },
  {
    id: 'L2a',
    display_name: 'L2a',
    class: 'LINE',
    family: 'L2',
    divergence_pct: 25.0,
    copy_count: 180_000,
    total_bp: 72_000_000,
    consensus_length: 400,
    cpg_density: 0.19,
    gc_content: 0.382,
    stacking_dg37: -1.23,
    wrapping_energy: 15.3,
    ndr_score: 0.15,
    periodicity_power: 0.17,
    silencing_primary: 'none',
    silencing_confidence: 0.88,
    reactivation_score: 0.00,
    reactivation_contexts: [],
    epic_v2_probes: 250,
    retro_age_probes: 0,
    has_intact_orfs: false,
    is_active: false,
    clinically_implicated: false,
  },

  // ── DNA transposons ─────────────────────────────────────────────────
  {
    id: 'hAT_Charlie',
    display_name: 'hAT-Charlie',
    class: 'DNA',
    family: 'hAT-Charlie',
    divergence_pct: 22.0,
    copy_count: 280_000,
    total_bp: 84_000_000,
    consensus_length: 300,
    cpg_density: 0.15,
    gc_content: 0.370,
    stacking_dg37: -1.18,
    wrapping_energy: 14.8,
    ndr_score: 0.14,
    periodicity_power: 0.15,
    silencing_primary: 'none',
    silencing_confidence: 0.85,
    reactivation_score: 0.00,
    reactivation_contexts: [],
    epic_v2_probes: 180,
    retro_age_probes: 0,
    has_intact_orfs: false,
    is_active: false,
    clinically_implicated: false,
  },
  {
    id: 'TcMar_Tigger',
    display_name: 'TcMar-Tigger',
    class: 'DNA',
    family: 'TcMar-Tigger',
    divergence_pct: 20.0,
    copy_count: 150_000,
    total_bp: 60_000_000,
    consensus_length: 400,
    cpg_density: 0.17,
    gc_content: 0.375,
    stacking_dg37: -1.20,
    wrapping_energy: 15.0,
    ndr_score: 0.15,
    periodicity_power: 0.16,
    silencing_primary: 'none',
    silencing_confidence: 0.82,
    reactivation_score: 0.00,
    reactivation_contexts: [],
    epic_v2_probes: 120,
    retro_age_probes: 0,
    has_intact_orfs: false,
    is_active: false,
    clinically_implicated: false,
  },
];

// Full dossier mock for HERV-K (HML-2)
export const MOCK_HERVK_DETAIL: TEFamilyDetail = {
  // Base TEFamily fields (same as MOCK_FAMILIES[0])
  id: 'HERVK_HML2',
  display_name: 'HERV-K (HML-2)',
  class: 'LTR',
  family: 'ERVK',
  divergence_pct: 2.3,
  copy_count: 1_200,
  total_bp: 11_400_000,
  consensus_length: 9_472,
  cpg_density: 1.14,
  gc_content: 0.482,
  stacking_dg37: -1.42,
  wrapping_energy: 17.8,
  ndr_score: 0.45,
  periodicity_power: 0.35,
  silencing_primary: 'mixed',
  silencing_confidence: 0.92,
  reactivation_score: 0.90,
  reactivation_contexts: ['aging', 'dnmti', 'tet2_lof', 'setdb1_lof'],
  epic_v2_probes: 127,
  retro_age_probes: 18,
  has_intact_orfs: true,
  is_active: true,
  clinically_implicated: true,

  // Detail extensions
  silencing_breakdown: [
    { mechanism: 'DNA methylation', proportion: 0.45, color: '#4ECDC4', evidence: 'curated' },
    { mechanism: 'SETDB1/H3K9me3', proportion: 0.30, color: '#F0A500', evidence: 'curated' },
    { mechanism: 'ZNF/KRAB-ZFP', proportion: 0.15, color: '#8B5CF6', evidence: 'curated' },
    { mechanism: 'piRNA pathway', proportion: 0.10, color: '#F43F5E', evidence: 'heuristic' },
  ],

  chr_density: [
    { chr: 'chr1', density: 0.42 },
    { chr: 'chr2', density: 0.35 },
    { chr: 'chr3', density: 0.48 },
    { chr: 'chr4', density: 0.30 },
    { chr: 'chr5', density: 0.28 },
    { chr: 'chr6', density: 0.38 },
    { chr: 'chr7', density: 0.72 },
    { chr: 'chr8', density: 0.32 },
    { chr: 'chr9', density: 0.25 },
    { chr: 'chr10', density: 0.33 },
    { chr: 'chr11', density: 0.40 },
    { chr: 'chr12', density: 0.36 },
    { chr: 'chr13', density: 0.22 },
    { chr: 'chr14', density: 0.28 },
    { chr: 'chr15', density: 0.30 },
    { chr: 'chr16', density: 0.45 },
    { chr: 'chr17', density: 0.38 },
    { chr: 'chr18', density: 0.20 },
    { chr: 'chr19', density: 0.68 },
    { chr: 'chr20', density: 0.24 },
    { chr: 'chr21', density: 0.18 },
    { chr: 'chr22', density: 0.26 },
  ],

  top_probes: [
    { probe_id: 'cg06545761', gene: 'ZCCHC14', position: 'chr16:87441441', is_retro_age: true },
    { probe_id: 'cg16972240', gene: 'SEMA6B', position: 'chr19:4544574', is_retro_age: true },
    { probe_id: 'cg10505257', gene: 'MGRN1', position: 'chr16:4685437', is_retro_age: true },
    { probe_id: 'cg27457201', gene: 'RPTOR', position: 'chr17:80785718', is_retro_age: false },
    { probe_id: 'cg16755922', gene: null, position: 'chr7:4812890', is_retro_age: false },
  ],

  probe_coverage_fraction: 0.68,

  reactivation_detail: [
    {
      context: 'DNMTi (5-azacytidine)',
      evidence: 'STRONG',
      notes: 'Robust reactivation of HERVK env/gag in treated AML cell lines; dsRNA production confirmed.',
    },
    {
      context: 'Aging',
      evidence: 'STRONG',
      notes: 'Progressive demethylation of HERVK LTRs with age; detectable HERVK transcripts in centenarian blood.',
    },
    {
      context: 'TET2 loss-of-function',
      evidence: 'PREDICTED',
      notes: 'TET2 LOF causes global hypomethylation at CGIs overlapping HERVK; direct reactivation data pending Phase II.',
    },
    {
      context: 'SETDB1 knockout',
      evidence: 'STRONG',
      notes: 'SETDB1 KO derepresses >90% of HERVK loci via H3K9me3 loss; viral-like particles produced.',
    },
    {
      context: 'Embryonic (2-cell stage)',
      evidence: 'STRONG',
      notes: 'HERVK is naturally expressed at 2-cell to blastocyst stage; silenced post-implantation.',
    },
  ],

  viral_mimicry: 'dsRNA + retrovirus-like particles',

  representative_loci: [
    {
      label: 'HERVK-113',
      region: 'chr19:21841536-21850866',
      notes: 'Most recently integrated, polymorphic insertion. Intact env/gag ORFs.',
    },
    {
      label: 'HERVK-108',
      region: 'chr7:4622057-4631495',
      notes: 'Full-length provirus with intact LTRs. Reactivation hotspot in melanoma.',
    },
    {
      label: 'HERVK-102',
      region: 'chr3:112743479-112752846',
      notes: 'Near-complete provirus. Expressed in placenta and testicular germ cell tumors.',
    },
  ],

  references: [
    {
      citation: 'Liu X et al. (2023)',
      journal: 'Cell',
      summary: 'Comprehensive HERVK reactivation atlas across cancer types; identified tissue-specific LTR enhancer co-option.',
    },
    {
      citation: 'Saini SK et al. (2020)',
      journal: 'Nat Commun',
      summary: 'HERVK-derived peptides presented on HLA class I in melanoma; T-cell recognition confirmed.',
    },
    {
      citation: 'Griffin GK et al. (2021)',
      journal: 'Nature',
      summary: 'TET2/DNMT3A mutations in clonal hematopoiesis activate inflammatory gene programs including ERV-derived enhancers.',
    },
    {
      citation: 'Sheng W et al. (2018)',
      journal: 'Nat Genet',
      summary: 'SETDB1 loss triggers ERV-mediated innate immune activation via dsRNA sensing; therapeutic implications for checkpoint inhibitors.',
    },
  ],
};
