"""Build the FormalClaim 3D projection artifact + diagnostics report.

Outputs (deterministic given fixed random_state=0):
  internal/InSilico/projection/formal_claim_projection_v1.json
  internal/InSilico/projection/DIAGNOSTICS_v1.md

Re-running this script must produce byte-identical files.

Run via:
  uv run python scripts/build_formal_claim_projection.py
or
  make projection
"""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np

from polymer_genomics.formal_claims.feature_extractor import (
    FEATURE_NAMES,
    build_feature_matrix,
    load_all_formal_claims,
)
from polymer_genomics.formal_claims.projection import ProjectionResult, project

# Fixed for byte-determinism. Bumping invalidates artifact provenance.
RANDOM_STATE: int = 0
SCHEMA_VERSION: str = "v1"
METHOD: str = "pca-3d-from-feature-vector"
# Pinned generated_at — using a fixed string instead of datetime.now() so
# re-runs produce byte-identical files. Bump only when the pipeline materially
# changes.
GENERATED_AT: str = "2026-04-18T00:00:00Z"

REPO_ROOT: Path = Path(__file__).resolve().parents[1]
OUT_DIR: Path = REPO_ROOT / "internal" / "InSilico" / "projection"
ARTIFACT_PATH: Path = OUT_DIR / "formal_claim_projection_v1.json"
DIAGNOSTICS_PATH: Path = OUT_DIR / "DIAGNOSTICS_v1.md"

# Deterministic float rounding for stable JSON serialization across reruns.
COORD_DECIMALS: int = 6
LOADING_DECIMALS: int = 6
EVR_DECIMALS: int = 6


def _round(x: float, decimals: int) -> float:
    return float(np.round(x, decimals))


def _round_list(xs, decimals: int) -> list[float]:
    return [_round(v, decimals) for v in xs]


def build_artifact(
    result: ProjectionResult,
    topics: dict[str, str],
    outcomes: dict[str, str],
    depends_on: dict[str, list[str]],
) -> dict:
    """Build the JSON envelope from a ProjectionResult."""
    claims_payload = []
    for i, cid in enumerate(result.ids):
        coords = result.coords_3d[i]
        claims_payload.append(
            {
                "id": cid,
                "topic": topics.get(cid, ""),
                "outcome": outcomes.get(cid, ""),
                "depends_on": list(depends_on.get(cid, [])),
                "projection_3d": [
                    _round(coords[0], COORD_DECIMALS),
                    _round(coords[1], COORD_DECIMALS),
                    _round(coords[2], COORD_DECIMALS),
                ],
            }
        )

    top_features_per_pc = [
        [[name, _round(loading, LOADING_DECIMALS)] for name, loading in feats]
        for feats in result.top_features_per_pc
    ]

    dep = result.depends_on_distance_summary
    dep_payload = {
        "n_edges": dep["n_edges"],
        "mean_observed": (
            _round(dep["mean_observed"], COORD_DECIMALS)
            if dep["mean_observed"] is not None
            else None
        ),
        "mean_null": (
            _round(dep["mean_null"], COORD_DECIMALS) if dep["mean_null"] is not None else None
        ),
        "p_value": (
            _round(dep["p_value"], COORD_DECIMALS) if dep["p_value"] is not None else None
        ),
        "n_perm": dep["n_perm"],
    }

    return {
        "schema_version": SCHEMA_VERSION,
        "method": METHOD,
        "generated_at": GENERATED_AT,
        "random_state": RANDOM_STATE,
        "n_claims": len(result.ids),
        "feature_dim_total": len(FEATURE_NAMES),
        "feature_dim_kept_after_zero_var_drop": len(FEATURE_NAMES)
        - len(result.dropped_zero_variance_features),
        "feature_names": list(FEATURE_NAMES),
        "dropped_zero_variance_features": list(result.dropped_zero_variance_features),
        "explained_variance": _round_list(result.explained_variance, EVR_DECIMALS),
        "top_features_per_pc": top_features_per_pc,
        "silhouette": {
            "by_topic": (
                _round(result.silhouette_by_topic, COORD_DECIMALS)
                if result.silhouette_by_topic is not None
                else None
            ),
            "by_outcome": (
                _round(result.silhouette_by_outcome, COORD_DECIMALS)
                if result.silhouette_by_outcome is not None
                else None
            ),
        },
        "depends_on_distance": dep_payload,
        "claims": claims_payload,
    }


def build_diagnostics(
    artifact: dict,
    result: ProjectionResult,
    topics: dict[str, str],
) -> str:
    """Generate the DIAGNOSTICS_v1.md report from an artifact + result."""
    lines: list[str] = []
    lines.append("# FormalClaim Projection — DIAGNOSTICS v1")
    lines.append("")
    lines.append(
        f"> Auto-generated by `scripts/build_formal_claim_projection.py`. "
        f"Re-run with `make projection` to regenerate."
    )
    lines.append("")
    lines.append(f"- **Method**: {artifact['method']}")
    lines.append(f"- **Generated at**: `{artifact['generated_at']}` (pinned for byte-determinism)")
    lines.append(f"- **Random state**: `{artifact['random_state']}`")
    lines.append(f"- **N claims**: {artifact['n_claims']}")
    lines.append(
        f"- **Feature dim**: {artifact['feature_dim_total']} total → "
        f"{artifact['feature_dim_kept_after_zero_var_drop']} kept after zero-variance drop"
    )
    lines.append("")

    lines.append("## Explained variance")
    lines.append("")
    evr = artifact["explained_variance"]
    lines.append(f"| Component | Variance ratio | Cumulative |")
    lines.append(f"|---|---|---|")
    cum = 0.0
    for i, v in enumerate(evr, start=1):
        cum += v
        lines.append(f"| PC{i} | {v:.4f} | {cum:.4f} |")
    lines.append("")

    lines.append("## Top 5 features per PC (by |loading|)")
    lines.append("")
    for pc_idx, feats in enumerate(artifact["top_features_per_pc"], start=1):
        lines.append(f"### PC{pc_idx}")
        lines.append("")
        lines.append("| Feature | Signed loading |")
        lines.append("|---|---|")
        for name, loading in feats:
            lines.append(f"| `{name}` | {loading:+.4f} |")
        lines.append("")

    lines.append("## Silhouette scores (3D Euclidean)")
    lines.append("")
    sil = artifact["silhouette"]
    lines.append(f"- **By topic** (RC excluded — singleton class): `{sil['by_topic']}`")
    lines.append(f"- **By outcome**: `{sil['by_outcome']}`")
    lines.append("")
    lines.append(
        "Negative silhouette = anti-clustered (samples are closer to other classes "
        "than their own); near zero = no clustering signal; positive = clustered."
    )
    lines.append("")

    lines.append("## Dependency edge tightness (permutation test)")
    lines.append("")
    dep = artifact["depends_on_distance"]
    if dep["n_edges"] == 0:
        lines.append("No `depends_on` edges in corpus.")
    else:
        lines.append(
            f"- Observed mean distance over {dep['n_edges']} edges: `{dep['mean_observed']}`"
        )
        lines.append(
            f"- Null mean (random pairs, n_perm={dep['n_perm']}): `{dep['mean_null']}`"
        )
        lines.append(f"- Empirical p (observed ≤ null): `{dep['p_value']}`")
        lines.append("")
        if dep["mean_observed"] < dep["mean_null"]:
            lines.append(
                f"Observed edges are tighter than chance by "
                f"{dep['mean_null'] - dep['mean_observed']:.4f} units."
            )
        else:
            lines.append("Observed edges are NOT tighter than chance.")
    lines.append("")

    # Sparse regions: 3 most-isolated claims by mean distance to 5-NN.
    lines.append("## Most-isolated claims (top 3 by mean distance to 5-nearest neighbours)")
    lines.append("")
    pw = result.pairwise_distances.copy()
    np.fill_diagonal(pw, np.inf)
    knn_k = min(5, pw.shape[0] - 1)
    nn_distances = np.sort(pw, axis=1)[:, :knn_k]
    mean_nn = nn_distances.mean(axis=1)
    order = np.argsort(-mean_nn)[:3]
    lines.append("| Claim id | Topic | Mean distance to 5-NN |")
    lines.append("|---|---|---|")
    for idx in order:
        cid = result.ids[idx]
        lines.append(f"| `{cid}` | {topics.get(cid, '')} | {mean_nn[idx]:.4f} |")
    lines.append("")
    lines.append(
        "Sparse regions in the latent space — these are candidates for *targeted* "
        "next-batch encoding (more claims of similar shape would densify these corners)."
    )
    lines.append("")

    # Falsifiable structural prediction: D = mean intra-topic distance + 1 sigma.
    lines.append("## Falsifiable structural prediction")
    lines.append("")
    intra_distances: list[float] = []
    by_topic_idx: dict[str, list[int]] = {}
    for i, cid in enumerate(result.ids):
        by_topic_idx.setdefault(topics[cid], []).append(i)
    for topic, idxs in by_topic_idx.items():
        if len(idxs) < 2:
            continue
        for a in idxs:
            for b in idxs:
                if a < b:
                    intra_distances.append(float(result.pairwise_distances[a, b]))
    if intra_distances:
        mean_intra = float(np.mean(intra_distances))
        sd_intra = float(np.std(intra_distances))
        threshold = mean_intra + sd_intra
        lines.append(
            f"Mean intra-topic pairwise distance: `{mean_intra:.4f}` "
            f"(SD `{sd_intra:.4f}`). Threshold `D = mean + 1σ = {threshold:.4f}`."
        )
        lines.append("")
        lines.append(
            f"**Prediction**: any newly encoded claim assigned to an existing topic "
            f"should land within distance `{threshold:.4f}` of at least one prior "
            f"member of its topic. Falsified if a new claim's nearest same-topic "
            f"neighbour exceeds this threshold — would indicate the topic-localization "
            f"property of the embedding is weak and the structural feature blocks need "
            f"reweighting."
        )
    else:
        lines.append("Insufficient intra-topic samples to compute the prediction.")
    lines.append("")

    return "\n".join(lines)


def write_json_deterministic(path: Path, payload: dict) -> None:
    """Write JSON with stable formatting: sort_keys + indent=2 + trailing newline."""
    text = json.dumps(payload, sort_keys=True, indent=2, ensure_ascii=False) + "\n"
    path.write_text(text, encoding="utf-8")


def main() -> int:
    OUT_DIR.mkdir(parents=True, exist_ok=True)

    claims, topics = load_all_formal_claims()
    if not claims:
        raise SystemExit("No claims found under internal/InSilico/**/claims/*.json")

    ids, X, names = build_feature_matrix(claims, topics)
    outcomes = {cid: claims[cid].conclusion.outcome for cid in ids}
    depends_on = {cid: list(claims[cid].depends_on) for cid in ids if claims[cid].depends_on}

    result = project(
        ids=ids,
        X=X,
        feature_names=names,
        topics=topics,
        outcomes=outcomes,
        depends_on=depends_on,
        random_state=RANDOM_STATE,
    )

    artifact = build_artifact(result, topics, outcomes, depends_on)
    write_json_deterministic(ARTIFACT_PATH, artifact)

    diagnostics = build_diagnostics(artifact, result, topics)
    DIAGNOSTICS_PATH.write_text(diagnostics, encoding="utf-8")

    print(f"[projection] Wrote {ARTIFACT_PATH.relative_to(REPO_ROOT)}")
    print(f"[projection] Wrote {DIAGNOSTICS_PATH.relative_to(REPO_ROOT)}")
    print(f"[projection] N claims = {len(ids)}, feature dim = {len(names)}")
    print(
        f"[projection] explained variance: "
        + ", ".join(f"PC{i+1}={v:.3f}" for i, v in enumerate(result.explained_variance))
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
